# Generated by Django 4.2.16 on 2025-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Partially Accepted', 'Partially Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Compilation Error', 'Compilation Error'), ('Runtime Error', 'Runtime Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('In Queue', 'In Queue'), ('Processing', 'Processing'), ('Internal Error', 'Internal Error'), ('Exec Format Error', 'Exec Format Error'), ('Unknown', 'Unknown')], default='In Queue', max_length=50),
        ),
    ]
