# Generated by Django 4.2.16 on 2025-07-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_submission_error_submission_execution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('go', 'Go'), ('ruby', 'Ruby'), ('php', 'PHP'), ('typescript', 'TypeScript'), ('kotlin', 'Kotlin'), ('swift', 'Swift')], default='python', max_length=20),
        ),
    ]
