# Generated by Django 4.2.16 on 2025-07-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_problem_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='language',
        ),
        migrations.AddField(
            model_name='problem',
            name='language_id',
            field=models.IntegerField(choices=[(71, 'Python 3'), (54, 'C++ (GCC 9.2.0)'), (62, 'Java (OpenJDK 13.0.1)'), (63, 'JavaScript (Node.js 12.14.0)'), (50, 'C (GCC 9.2.0)'), (68, 'PHP (7.4.1)'), (70, 'Python 2'), (72, 'Ruby 2.7.0'), (60, 'Go (1.13.5)'), (73, 'Rust 1.40.0'), (52, 'C# (Mono 6.6.0.161)'), (61, 'Kotlin (1.3.70)'), (78, 'Kotlin (JVM 1.6.10)'), (80, 'TypeScript (3.7.4)'), (74, 'Swift (5.2.3)'), (79, 'Scala (2.13.4)'), (69, 'Perl (5.28.1)'), (65, 'R (4.0.0)'), (67, 'Pascal (FPC 3.0.4)'), (64, 'Lua (5.3.5)'), (75, 'Haskell (GHC 8.8.1)'), (76, 'Objective-C (Clang 7.0.1)'), (77, 'Groovy (3.0.3)'), (49, 'C (GCC 8.3.0)'), (55, 'C++ (GCC 8.3.0)'), (56, 'C++ (GCC 7.4.0)'), (57, 'C++ (GCC 6.3.0)'), (58, 'C++ (GCC 5.4.0)'), (59, 'C++ (GCC 4.9.2)')], default=71, help_text='Programming language for this problem.'),
        ),
    ]
